image: python

on: push

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - python3 -V

test-count:
  stage: test
  script:
    - python3 manage.py runserver

deploy-job:
  stage: deploy
  script:
    - echo "Terminou"
