image: python

on: push

jobs:
  build-job:
    stage: build
    script:
      - python3 -V

  test-job:
    stage: test
    script:
      - python3 manage.py runserver

  deploy-job:
    stage: deploy
    script:
      - echo "Terminou"
